version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    container_name : mongo-server
    ports:
      - "16025:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SERVER_PWD}
      - TZ=Asia/Seoul

    logging:
      options:
        max-size: "100m"
        max-file: "3"
