version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-stream
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "VCT_RABBIT_COOKIE"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ADMIN_NAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ADMIN_PASSWORD}
    depends_on:
      - application
  mongodb:
    image: mongo
    restart: always
    container_name : mongo-server
    ports:
      - "16025:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SERVER_PWD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_CONN}
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: "100m"
        max-file: "3"
  application:
    container_name: spring-vct
    image: openjdk:17-jdk
    build:
      context: ./VCTServer
      dockerfile: ./Dockerfile
    ports:
      - "1300:8080"
    
    environment:
      SPRING_DATA_MONGODB_HOST : mongo-server
      SPRING_DATA_MONGODB_PORT : 27017
      SPRING_DATA_MONGODB_USERNAME : mongo
      SPRING_DATA_MONGODB_PASSWORD : ${MONGO_SERVER_PWD}
      SPRING_DATA_MONGODB_DATABASE : ${MONGO_DATABASE_CONN}
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE : admin

      SPRING_OUTAPI_ID : ${SPRING_OUTAPI_ID}
      SPRING_OUTAPI_PWD : ${SPRING_OUTAPI_PWD}
      SPRING_OUTAPI_POS : ${SPRING_OUTAPI_POS}
      SPRING_OUTAPI_DIV : ${SPRING_OUTAPI_DIV}
      SPRING_OUTAPI_URL : ${SPRING_OUTAPI_URL}
      SPRING_OUTAPI_DATA : ${SPRING_OUTAPI_DATA}

      SPRING_JSOUP_URL : ${SPRING_JSOUP_URL}
      SPRING_JSOUP_NEWS_URL : ${SPRING_JSOUP_NEWS_URL}
      SPRING_JSOUP_THUMBNAIL_URL : ${SPRING_JSOUP_THUMBNAIL_URL}

      SPRING_JWT_SECRET_KEY : ${SPRING_JWT_SECRET_KEY}
    depends_on:
      - mongodb
#  wsNginx:
#    image: nginx
#    container_name: wsNginx
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/ssl:/etc/nginx/ssl
#    environment:
#      - TZ=Asia/Seoul
#    depends_on:
#      - application
#    links:
#      - application
