# Generated by Django 4.0.4 on 2022-06-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_Nick', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='VegetableCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=50)),
                ('coin_price', models.FloatField()),
                ('coin_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VegetablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable_name', models.CharField(max_length=30)),
                ('vegetable_price', models.IntegerField()),
                ('vegetable_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_point', models.FloatField()),
                ('pc_cucumber', models.IntegerField()),
                ('pc_potato', models.IntegerField()),
                ('pc_sweatpt', models.IntegerField()),
                ('pc_galic', models.IntegerField()),
                ('pc_cabbage', models.IntegerField()),
                ('pc_user', models.ForeignKey(db_column='pc_user', on_delete=django.db.models.deletion.CASCADE, related_name='Purchase', to='VegetableAPI.user')),
            ],
            options={
                'db_table': 'PurchaseCoin',
            },
        ),
    ]
